# Generated by Django 3.0.3 on 2020-03-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shoe_size',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
